version: '3.8'

services:
  database:
    container_name: cilist-db
    image: mwbowo/cilistx-db:1.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=s3k0l4hd3v0p5
      - MYSQL_DATABASE=people
  
  backend:
    container_name: cilist-be
    image: mwbowo/cilisx-be:1.0
    ports:
      - "5000:5000"
    depends_on:
      - database
      - frontend
  
  frontend:
    container_name: cilist-fe
    image: mwbowo/cilistx-fe:1.0
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
