version: '3.8'

services:
  database:
    container_name: cilist-db
    image: cilist/db
    ports:
      - "3306:3306"
    environment:
      - BASE_URL_PORT=5000
      - MYSQL_ROOT_PASSWORD=s3k0l4hd3v0p5
      - DATABASE_USERNAME=people
      - DATABASE_PASSWORD=people
      - DATABASE_DATABASE=people
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
  backend:
    container_name: cilist-be
    image: cilist/be
    ports:
      - "5000:5000"
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 500m

  frontend:
    container_name: cilist-fe
    image: cilist/fe
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 500m